import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HelpWidget } from "../components/HelpWidget";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Live Chat Support App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Live <span className="text-[hsl(280,100%,70%)]">Chat</span> Support App 
          </h1>
         
        </div>
        <HelpWidget/>
      </main>
    </>
  );
};

export default Home;
